name: Correct Indonesian Geography
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-versiom: 3.10
    - name: Install dependencies
      run:
        make install
